name: Archive & upload template without demo

on:
  release:
    types:
      - created

jobs:
  build:
    name: Archive & upload template without demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Archive template and license
        run: |
          zip -r discordfx-${{ github.event.release.tag_name }}.zip README.md LICENSE discordfx
      - name: Upload archive
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} 
          asset_path: ./discordfx-${{ github.event.release.tag_name }}.zip
          asset_name: discordfx-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
